const GROUPS: string[][] = [
  ["berlin", "berlino"],
  ["köln", "colonia", "koln", "cologne"],
  ["münchen", "monaco di baviera", "munchen", "munich"],
  ["hamburg", "amburgo"],
  ["frankfurt", "frankfurt am main", "francoforte"],
  ["stuttgart", "stoccarda"],
  ["nürnberg", "norimberga", "nurnberg", "nuremberg"],
  ["leipzig", "lipsia"],
  ["bremen", "brema"],
  ["dresden", "dresda"],
  ["paris", "parigi"],
  ["marseille", "marsiglia"],
  ["lyon", "lione"],
  ["toulouse", "tolosa"],
  ["nice", "nizza"],
  ["strasbourg", "strasburgo"],
  ["lille", "lilla"],
  ["london", "londra"],
  ["edinburgh", "edimburgo"],
  ["barcelona", "barcellona"],
  ["sevilla", "siviglia", "seville"],
  ["zaragoza", "saragozza"],
  ["málaga", "malaga"],
  ["lisboa", "lisbona", "lisbon"],
  ["den haag", "l'aia", "the hague", "aia"],
  ["antwerpen", "anversa", "antwerp"],
  ["gent", "gand", "ghent"],
  ["liège", "liegi", "liege"],
  ["brussels", "bruxelles"],
  ["wien", "vienna"],
  ["salzburg", "salisburgo"],
  ["zürich", "zurigo", "zurich"],
  ["genève", "ginevra", "geneva", "geneve"],
  ["basel", "basilea"],
  ["bern", "berna"],
  ["luzern", "lucerna", "lucerne"],
  ["st. gallen", "san gallo", "st gallen"],
  ["warszawa", "varsavia", "warsaw"],
  ["kraków", "cracovia", "krakow"],
  ["wrocław", "breslavia", "wroclaw"],
  ["gdańsk", "danzica", "gdansk"],
  ["bucurești", "bucarest", "bucharest", "bucuresti"],
  ["praha", "praga", "prague"],
  ["athens", "atene", "αθήνα"],
  ["thessaloniki", "salonicco"],
  ["patras", "patrasso"],
  ["zagreb", "zagabria"],
  ["split", "spalato"],
  ["sofia", "софия"],
  ["beograd", "belgrado", "belgrade"],
  ["kyiv", "kiev"],
  ["lviv", "leopoli", "львів"],
  ["odesa", "odessa"],
  ["tbilisi", "თბილისი"],
  ["istanbul", "i̇stanbul"],
  ["izmir", "smirne", "i̇zmir"],
  ["tirana", "tiranë", "tirane"],
  ["durrës", "durazzo", "durres"],
];

export function expandCitySynonyms(city: string): string[] {
  const q = city.trim().toLowerCase();
  if (!q) return [city];
  const group = GROUPS.find(g => g.includes(q));
  return group ? [...new Set(group)] : [city];
}
