export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  IT: ["Roma", "Milano", "Napoli", "Torino", "Bologna", "Firenze", "Bari", "Palermo", "Genova", "Venezia", "Verona", "Padova", "Brescia", "Bergamo", "Modena", "Parma", "Rimini", "Catania", "Cagliari", "Trieste"],
  DE: ["Berlino", "Monaco di Baviera", "Amburgo", "Colonia", "Francoforte", "Stoccarda", "Düsseldorf", "Norimberga", "Hannover", "Lipsia", "Dortmund", "Brema"],
  FR: ["Parigi", "Marsiglia", "Lione", "Tolosa", "Nizza", "Nantes", "Strasburgo", "Lilla", "Bordeaux", "Reims"],
  ES: ["Madrid", "Barcellona", "Valencia", "Siviglia", "Bilbao", "Malaga", "Alicante", "Saragozza", "Marbella", "Almería"],
  PT: ["Lisbona", "Porto", "Braga", "Faro", "Coimbra"],
  NL: ["Amsterdam", "Rotterdam", "L'Aia", "Utrecht", "Eindhoven", "Waalwijk"],
  BE: ["Bruxelles", "Anversa", "Gand", "Liegi", "Charleroi", "Namur"],
  AT: ["Vienna", "Salisburgo", "Innsbruck", "Linz", "Graz"],
  CH: ["Zurigo", "Ginevra", "Basilea", "Berna", "Lugano", "Lucerna", "San Gallo"],
  GB: ["Londra", "Manchester", "Birmingham", "Liverpool", "Leeds", "Glasgow", "Bristol", "Sheffield", "Edimburgo"],
  PL: ["Varsavia", "Cracovia", "Breslavia", "Danzica", "Poznań", "Łódź"],
  RO: ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  CZ: ["Praga", "Brno", "Plzeň", "Ostrava"],
  SK: ["Bratislava", "Košice"],
  HU: ["Budapest", "Debrecen", "Győr"],
  GR: ["Atene", "Salonicco", "Patrasso"],
  HR: ["Zagabria", "Spalato", "Rijeka"],
  BG: ["Sofia", "Plovdiv", "Varna"],
  RS: ["Belgrado", "Novi Sad", "Niš"],
  UA: ["Kiev", "Leopoli", "Odessa", "Dnipro"],
  GE: ["Tbilisi", "Batumi", "Kutaisi"],
  TR: ["Istanbul", "Ankara", "Smirne", "Antalya"],
  AL: ["Tirana", "Durazzo"],
  US: ["New York", "Los Angeles", "Chicago", "Miami", "Houston", "Dallas", "Boston", "Philadelphia", "Phoenix", "San Francisco", "Seattle", "Denver", "Las Vegas", "Orlando", "Atlanta"],
};
